import type { Metadata } from 'next';
import './globals.css';
import { SanityLive } from '@/sanity/live';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { Toaster, TooltipProvider } from '@snoomleng/ui';
import { Josefin_Slab, Open_Sans } from 'next/font/google';
import { twMerge } from 'tailwind-merge';
import clsx from 'clsx';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const heading = Josefin_Slab({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  style: 'normal',
  variable: '--font-next-heading',
});

export const body = Open_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800'],
  style: 'normal',
  variable: '--font-next-body',
});

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
      data-scroll-behavior="smooth"
      suppressHydrationWarning
    >
      <body
        className={twMerge(
          clsx(
            `${body.variable} ${heading.variable}`,
            'min-h-full flex flex-col',
          ),
        )}
      >
        <TooltipProvider>
          <Header />
          {children}
          <Footer />
        </TooltipProvider>

        <Toaster richColors position="bottom-center" duration={2} closeButton />
        <SanityLive />
      </body>
    </html>
  );
}
