import { fn } from 'storybook/test';

export const mockFormAction = fn(async () => {
  return {
    success: true,
    message: 'Form Submission Success',
  };
});

export const mockHero = {
  _id: '1dc35efd-93c2-45c9-87fe-f1f0b584c301',
  actions: [
    {
      _key: '253cae6464ff',
      href: '#projects',
      label: 'Projects',
    },
    {
      _key: 'dce757cc5f68',
      href: '#contact',
      label: 'Contact',
    },
  ],
  body: [
    {
      _key: 'f140dd5e9dbe',
      _type: 'block',
      children: [
        {
          _key: '91413483107f',
          _type: 'span',
          marks: [],
          text: 'I’m a',
        },
        {
          _key: 'ac8e1e6fc9a8',
          _type: 'span',
          marks: ['highlight'],
          text: ' full-stack developer',
        },
        {
          _key: '116ca4c31726',
          _type: 'span',
          marks: [],
          text: ' focused on building modern, scalable web applications with clean architecture, thoughtful UX, and reliable engineering. I enjoy turning ideas into polished products—from the interface users see to the systems that ',
        },
        {
          _key: 'b6d87b462893',
          _type: 'span',
          marks: ['highlight'],
          text: 'power them',
        },
        {
          _key: 'c4ee88b3e6e7',
          _type: 'span',
          marks: [],
          text: '.',
        },
      ],
      markDefs: [],
      style: 'normal',
    },
  ],
  imageAlt: 'my cartoon',
  imageUrl:
    'https://cdn.sanity.io/images/h5ref3kt/production/5ad6f5c06b40ec1a79f9c64a2f1117bd644303db-500x500.png',
  position: ['Software Engineer', 'Builder'],
  title: 'Building thoughtful digital experiences',
};

export const mockAbout = {
  body: [
    {
      _key: 'd285b8c927aa',
      _type: 'block',
      children: [
        {
          _key: '54112dcd5d6b',
          _type: 'span',
          marks: [],
          text: 'A software engineer and Computer Science student passionate about building modern, scalable web applications.',
        },
      ],
      level: 1,
      listItem: 'bullet',
      markDefs: [],
      style: 'normal',
    },
    {
      _key: '001b0e95f7af',
      _type: 'block',
      children: [
        {
          _key: '54112dcd5d6b',
          _type: 'span',
          marks: [],
          text: 'With a background in editorial photography, I bring a creative perspective into engineering — combining design thinking with technical problem-solving. I specialize in full-stack development with React, Next.js, TypeScript, Node.js, PostgreSQL, and cloud technologies.',
        },
      ],
      level: 1,
      listItem: 'bullet',
      markDefs: [],
      style: 'normal',
    },
    {
      _key: 'a82917d10300',
      _type: 'block',
      children: [
        {
          _key: '54112dcd5d6b',
          _type: 'span',
          marks: [],
          text: 'I enjoy building products, designing reliable systems, and continuously learning how technology works from the interface to the infrastructure behind it.',
        },
      ],
      level: 1,
      listItem: 'bullet',
      markDefs: [],
      style: 'normal',
    },
  ],
  workflows: [
    {
      _key: '26f02f328b3a',
      body: 'I start by understanding the problem, defining the goals, and thinking through the architecture before writing too much code. I break the project into smaller pieces, choose the right technologies, design the data flow, and establish a maintainable structure that can grow with the product.',
      title: 'Plan & Architect',
    },
    {
      _key: 'fa92e96ee5bf',
      body: 'I turn the plan into a working product, building from the core functionality outward. I focus on reusable components, type-safe APIs, database design, validation, authentication, and a consistent user experience while keeping the codebase clean and easy to evolve.',
      title: 'Build & Integrate',
    },
    {
      _key: '58ae3d544ca7',
      body: 'Once the product works, I focus on making it reliable and production-ready. I test critical flows, improve performance and accessibility, fix edge cases, and refine the experience before deploying. I then use the feedback and lessons from each project to continuously improve my next one.',
      title: 'Test, Refine & Ship',
    },
  ],
  mode: ['Remote', 'Intl', 'Full Time', 'Part Time'],
};

export const mockTechs = [
  {
    _id: '2a0b302b-425a-417f-9b0d-7dc69cdcdbf4',
    icon: 'reacthookform',
    name: 'React Hook Form',
  },
  {
    _id: '34ec05d8-1048-47c0-baaa-8cfda2630b51',
    icon: 'postgresql',
    name: 'PostgreSQL',
  },
  {
    _id: '3b1931fa-eb4e-4709-818e-14bd43ae211c',
    icon: 'tanstack',
    name: 'Tanstack',
  },
  {
    _id: '51b64b3a-fc5b-4284-adaa-7f733c5704b3',
    icon: 'betterauth',
    name: 'BetterAuth',
  },
  {
    _id: '5da43751-e0f1-4033-8fb2-698149ec7bd0',
    icon: 'react',
    name: 'React',
  },
  {
    _id: '625b3c25-e01c-4b88-a433-180361084ef0',
    icon: 'gsap',
    name: 'GSAP',
  },
  {
    _id: '67ce88d4-69ee-4a9b-8019-499b4d08961c',
    icon: 'zod',
    name: 'Zod',
  },
  {
    _id: '7b2ad5a7-41d7-4c56-b988-ead535a33beb',
    icon: 'storybook',
    name: 'Storybook',
  },
  {
    _id: '7f22e4d6-dcff-4d5f-bbd6-b0f14bdd49cc',
    icon: 'expressjs',
    name: 'Express.js',
  },
  {
    _id: '86b6cb95-f6c3-4af2-8749-c38be5b1b62d',
    icon: 'linux',
    name: 'Linux',
  },
  {
    _id: '96c149ec-4c48-45ba-bddf-f269784a750d',
    icon: 'typescript',
    name: 'TypeScript',
  },
  {
    _id: 'a066e089-59de-417b-b5c3-88e69df34b65',
    icon: 'vitest',
    name: 'Vitest',
  },
  {
    _id: 'a1ac8220-c08c-4487-88ef-b661a022f24c',
    icon: 'nginx',
    name: 'Nginx',
  },
  {
    _id: 'a9a46afd-c4ea-45a0-ac66-176f5027ac96',
    icon: 'tailwindcss',
    name: 'TailwindCSS',
  },
  {
    _id: 'b32037a8-ff8a-4658-836d-d456c706b39d',
    icon: 'sanity',
    name: 'Sanity',
  },
  {
    _id: 'b6b40743-4bdf-44f7-b6c5-6bb94cd9e06b',
    icon: 'github',
    name: 'Git/GitHub',
  },
  {
    _id: 'c150192f-3da3-4dd5-b87d-4d67fc1749d7',
    icon: 'vim',
    name: 'Vim',
  },
  {
    _id: 'c8883c39-b834-46d0-9f76-8fa64c1cf9b8',
    icon: 'nextjs',
    name: 'Next.js',
  },
  {
    _id: 'd20297e0-4817-4445-8f33-38a5457acbfc',
    icon: 'clerk',
    name: 'Clerk',
  },
  {
    _id: 'd7f64f5a-8c68-4850-ae3a-2cefb06cd885',
    icon: 'aws',
    name: 'AWS',
  },
  {
    _id: 'd8060586-d585-40a9-a5d2-c4b7f9fb4a0f',
    icon: 'docker',
    name: 'Docker',
  },
  {
    _id: 'e3798b49-1d40-4a80-bf59-4311dd29050a',
    icon: 'neon',
    name: 'Neon',
  },
  {
    _id: 'fa1308fe-ff1f-4e70-8136-1a891a5cd9b6',
    icon: 'drizzle',
    name: 'Drizzle ORM',
  },
  {
    _id: 'fbcb424f-0b1e-4988-9a41-4217f552bb18',
    icon: 'shadcn',
    name: 'shadCn',
  },
];

export const mockProject = [
  {
    _id: '64bd3159-b9f3-4344-a044-ec479c0663c1',
    endedAt: '2026-08-20',
    excerpt:
      'A modern full-stack application built with a focus on thoughtful user experience, scalable architecture, and maintainable code.',
    links: [
      {
        _key: 'aa139a47ff06',
        label: 'Production',
        url: 'https://www.snoomleng.com',
      },
      {
        _key: '7ded3bfe7748',
        label: 'Repo',
        url: 'https://github.com/saisaynoomleng/snoomleng',
      },
    ],
    name: 'snoomleng',
    slug: 'snoomleng',
    stacks: [
      'Next.js',
      'React',
      'TypeScript',
      'Zod',
      'TailwindCSS',
      'shadCn',
      'Storybook',
      'React Hook Form',
      'React Portable Text',
      'Tanstack Query',
      'GSAP',
      'express.js',
      'Sanity',
      'PostgreSQL',
      'Neon',
      'Drizzle',
      'BetterAuth',
      'React Email',
      'GitHub Actions',
      'CI/CD',
      'Bash',
      'Linux',
      'Git/GitHub',
      'Vitest',
      'Playwright',
      'Certbot',
      'Nginx',
      'Docker',
      'AWS CloudFront',
      'AWS CloudWatch',
      'AWS EC2',
      'AWS ECR',
      'AWS SQS',
      'AWS Lambda',
      'AWS SES',
      'AWS Secrets Manager',
    ],
    startedAt: '2026-08-08',
    type: 'Personal Project',
  },
  {
    type: 'Personal Project',
    _id: '64bd3159-b9f3-4344-a044-ec479c0663cssdf1',
    endedAt: '2026-08-20',
    excerpt:
      'A modern full-stack application built with a focus on thoughtful user experience, scalable architecture, and maintainable code.',
    links: [
      {
        _key: 'aa139a47ff06',
        label: 'Production',
        url: 'https://www.snoomleng.com',
      },
      {
        _key: '7ded3bfe7748',
        label: 'Repo',
        url: 'https://github.com/saisaynoomleng/snoomleng',
      },
    ],
    name: 'snoomleng',
    slug: 'snoomleng',
    stacks: [
      'Next.js',
      'React',
      'TypeScript',
      'Zod',
      'TailwindCSS',
      'shadCn',
      'Storybook',
      'React Hook Form',
      'React Portable Text',
      'Tanstack Query',
      'GSAP',
      'express.js',
      'Sanity',
      'PostgreSQL',
      'Neon',
      'Drizzle',
      'BetterAuth',
      'React Email',
      'GitHub Actions',
      'CI/CD',
      'Bash',
      'Linux',
      'Git/GitHub',
      'Vitest',
      'Playwright',
      'Certbot',
      'Nginx',
      'Docker',
      'AWS CloudFront',
      'AWS CloudWatch',
      'AWS EC2',
      'AWS ECR',
      'AWS SQS',
      'AWS Lambda',
      'AWS SES',
      'AWS Secrets Manager',
    ],
    startedAt: '2026-08-08',
  },
  {
    type: 'Personal Project',
    _id: '64bd3159sfasdf-b9f3-4344-a044-ec479c0663c1',
    endedAt: '2026-08-20',
    excerpt:
      'A modern full-stack application built with a focus on thoughtful user experience, scalable architecture, and maintainable code.',
    links: [
      {
        _key: 'aa139a47ff06',
        label: 'Production',
        url: 'https://www.snoomleng.com',
      },
      {
        _key: '7ded3bfe7748',
        label: 'Repo',
        url: 'https://github.com/saisaynoomleng/snoomleng',
      },
    ],
    name: 'snoomleng',
    slug: 'snoomleng',
    stacks: [
      'Next.js',
      'React',
      'TypeScript',
      'Zod',
      'TailwindCSS',
      'shadCn',
      'Storybook',
      'React Hook Form',
      'React Portable Text',
      'Tanstack Query',
      'GSAP',
      'express.js',
      'Sanity',
      'PostgreSQL',
      'Neon',
      'Drizzle',
      'BetterAuth',
      'React Email',
      'GitHub Actions',
      'CI/CD',
      'Bash',
      'Linux',
      'Git/GitHub',
      'Vitest',
      'Playwright',
      'Certbot',
      'Nginx',
      'Docker',
      'AWS CloudFront',
      'AWS CloudWatch',
      'AWS EC2',
      'AWS ECR',
      'AWS SQS',
      'AWS Lambda',
      'AWS SES',
      'AWS Secrets Manager',
    ],
    startedAt: '2026-08-08',
  },
];

export const mockEmployments = [
  {
    _id: '4c2b8cf1-394f-472c-bcaf-6155d4dac9cb',
    body: [
      {
        _key: '0e95c7fc1799',
        _type: 'block',
        children: [
          {
            _key: '7d0e6d87206d',
            _type: 'span',
            marks: [],
            text: 'Provided reliable on-demand delivery services while managing high-volume orders, route optimization, and customer communication in a fast-paced environment.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
    ],
    companyName: 'DoorDash',
    endedAt: null,
    name: 'Delivery Driver',
    startedAt: '2025-09-10',
  },
  {
    _id: '5620dfaf-429e-43a7-8f55-66f868b181a5',
    body: [
      {
        _key: '505e62aee987',
        _type: 'block',
        children: [
          {
            _key: '74d6bb3fece6',
            _type: 'span',
            marks: [],
            text: 'Specialized in editorial, commercial, wedding, and pre-wedding photography, delivering high-quality visual content tailored to client needs',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '6bbbb48f0b23',
        _type: 'block',
        children: [
          {
            _key: 'bf9b94ac5fa6',
            _type: 'span',
            marks: [],
            text: 'Collaborated with prominent franchises including Miss Universe Myanmar and Super Model Myanmar, as well as various local companies and agencies',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '79be363faf41',
        _type: 'block',
        children: [
          {
            _key: 'ac94899cb329',
            _type: 'span',
            marks: [],
            text: 'Participated in workshops and events across Southeast Asia, earning certificates of completion',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
    ],
    companyName: 'GreenMile Production',
    endedAt: '2023-10-23',
    name: 'Founder/Photographer',
    startedAt: '2016-12-25',
  },
];
