#===============================
# Stage 1: Dependencies
#===============================

ARG NODE_VERSION=24-alpine3.24

FROM node:${NODE_VERSION} AS dependencies

WORKDIR /app

RUN corepack enable pnpm && corepack prepare pnpm@11.0.0 --activate

COPY package.json pnpm*.yaml ./
COPY ./apps/portfolio/package.json ./apps/portfolio/package.json
COPY ./packages/ui/package.json ./packages/ui/package.json
COPY ./packages/utils/package.json ./packages/utils/package.json

RUN --mount=type=cache,id=pnpm,target=/root/.local/share/pnpm/store \
pnpm i --frozen-lockfile

#===============================
# Stage 2: Build
#===============================
FROM dependencies AS build

WORKDIR /app

COPY . .

ARG NEXT_PUBLIC_SANITY_DATASET=production
ARG NEXT_PUBLIC_SANITY_PROJECT_ID=h5ref3kt
ARG NEXT_PUBLIC_API_URL=https://api.snoomleng.com

ENV NEXT_PUBLIC_SANITY_DATASET=${NEXT_PUBLIC_SANITY_DATASET}
ENV NEXT_PUBLIC_SANITY_PROJECT_ID=${NEXT_PUBLIC_SANITY_PROJECT_ID}
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

RUN pnpm --filter portfolio build


#===============================
# Stage 3: Runtime
#===============================

FROM node:${NODE_VERSION} AS runtime

RUN addgroup -S portfolio && adduser -S portfolio -G portfolio

WORKDIR /app

USER portfolio

ENV NODE_ENV=production
ENV PORT=3000

COPY --from=build --chown=portfolio:portfolio \
/app/apps/portfolio/.next/standalone ./

COPY --from=build --chown=portfolio:portfolio \
/app/apps/portfolio/.next/static ./apps/portfolio/.next/static

COPY --from=build --chown=portfolio:portfolio \
/app/apps/portfolio/public ./apps/portfolio/public

EXPOSE 3000

CMD [ "node", "apps/portfolio/server.js" ]

