/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/extract.json
export type BlogCategoryReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'blogCategory';
};

export type BlogFocusReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'blogFocus';
};

export type Blog = {
  _id: string;
  _type: 'blog';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  publishedAt?: string;
  excerpt?: string;
  body?: BlockContent;
  mainImage?: ImageWithAlt;
  category?: BlogCategoryReference;
  focus?: BlogFocusReference;
  seo?: Seo;
};

export type Seo = {
  _type: 'seo';
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: ImageWithAlt;
  noIndex?: boolean;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type ImageWithAlt = {
  _type: 'imageWithAlt';
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
      listItem?: 'bullet';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }
  | ({
      _key: string;
    } & ImageWithAlt)
>;

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type BlogFocus = {
  _id: string;
  _type: 'blogFocus';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
};

export type BlogCategory = {
  _id: string;
  _type: 'blogCategory';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  mainImage?: ImageWithAlt;
};

export type Employment = {
  _id: string;
  _type: 'employment';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  startedAt?: string;
  endedAt?: string;
  body?: BlockContent;
  companyName?: string;
};

export type Project = {
  _id: string;
  _type: 'project';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  excerpt?: string;
  startedAt?: string;
  endedAt?: string;
  stacks?: Array<string>;
  links?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  body?: BlockContent;
  type?: 'property' | 'portfolio' | 'health-care' | 'e-commerce';
  mainImage?: ImageWithAlt;
  seo?: Seo;
};

export type Technology = {
  _id: string;
  _type: 'technology';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  icon?: string;
  type?:
    | 'frontend'
    | 'backend'
    | 'ai'
    | 'tooling'
    | 'devops'
    | 'badge'
    | 'cloud-and-infrastructure';
};

export type About = {
  _id: string;
  _type: 'about';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  body?: BlockContent;
  expertises?: Array<{
    title?: string;
    body?: BlockContent;
    _key: string;
  }>;
  workFlow?: Array<{
    title?: string;
    body?: string;
    _key: string;
  }>;
};

export type Hero = {
  _id: string;
  _type: 'hero';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  position?: Array<string>;
  title?: string;
  body?: BlockContent;
  mainImage?: ImageWithAlt;
  actions?: Array<{
    label?: string;
    href?: string;
    _key: string;
  }>;
};

export type SiteSetting = {
  _id: string;
  _type: 'siteSetting';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  primaryLogo?: ImageWithAlt;
  secondaryLogo?: ImageWithAlt;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  contactInfo?: {
    email?: string;
    linkedInUrl?: string;
    leetCodeURL?: string;
    gitHubURL?: string;
    city?: string;
    state?: string;
  };
  mode?: Array<string>;
  isAvailable?: boolean;
  availability?: string;
  navigation?: Array<{
    label?: string;
    href?: string;
    isButton?: boolean;
    _type: 'navLink';
    _key: string;
  }>;
  footerColumns?: Array<{
    columnTitle?: string;
    columnLinks?: Array<{
      label?: string;
      href?: string;
      _type: 'columnLink';
      _key: string;
    }>;
    _type: 'footerColumn';
    _key: string;
  }>;
  footerText?: string;
};

export type SocialLink = {
  _type: 'socialLink';
  platform?: 'linked-in' | 'git-hub' | 'leet-code';
  url?: string;
  icon?: string;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type MediaFolderReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'media.folder';
};

export type MediaFolder = {
  _id: string;
  _type: 'media.folder';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  parent?: MediaFolderReference;
};

export type MediaTag = {
  _id: string;
  _type: 'media.tag';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | BlogCategoryReference
  | BlogFocusReference
  | Blog
  | Seo
  | SanityImageAssetReference
  | ImageWithAlt
  | BlockContent
  | Slug
  | BlogFocus
  | BlogCategory
  | Employment
  | Project
  | Technology
  | About
  | Hero
  | SiteSetting
  | SocialLink
  | SanityImageCrop
  | SanityImageHotspot
  | MediaFolderReference
  | MediaFolder
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/query.ts
// Variable: LOGO_QUERY
// Query: *[_type == 'siteSetting'][0]{  "imageUrl": primaryLogo.asset->url,  "imageAlt": primaryLogo.alt}
export type LOGO_QUERY_RESULT = {
  imageUrl: string | null;
  imageAlt: string | null;
} | null;

// Source: src/sanity/query.ts
// Variable: SETTING_QUERY
// Query: *[_type == 'siteSetting'][0]{    "branding": {      siteName,      "primaryLogo": {        "imageUrl": primaryLogo.asset->url,        "imageAlt": primaryLogo.alt,      },      "secondaryLogo": {        "imageUrl": secondaryLogo.asset->url,        "imageAlt": secondaryLogo.alt,      },      socialLinks[]{        _key,        icon,        platform,        url      },      contactInfo{        city,        email,        githubURL,        leetCodeURL,        linkedInUrl,        state      },      mode[],      isAvailable,    },  "navigation": navigation[]{                  _key,                  href,                  isButton,                  label                },  "footer": {    "columns": footerColumns[]{      _key,      columnLinks[]{        _key,        href,        label      }    },    "text": footerText  }}
export type SETTING_QUERY_RESULT = {
  branding: {
    siteName: string | null;
    primaryLogo: {
      imageUrl: string | null;
      imageAlt: string | null;
    };
    secondaryLogo: {
      imageUrl: string | null;
      imageAlt: string | null;
    };
    socialLinks: Array<{
      _key: string;
      icon: string | null;
      platform: 'git-hub' | 'leet-code' | 'linked-in' | null;
      url: string | null;
    }> | null;
    contactInfo: {
      city: string | null;
      email: string | null;
      githubURL: null;
      leetCodeURL: string | null;
      linkedInUrl: string | null;
      state: string | null;
    } | null;
    mode: Array<string> | null;
    isAvailable: boolean | null;
  };
  navigation: Array<{
    _key: string;
    href: string | null;
    isButton: boolean | null;
    label: string | null;
  }> | null;
  footer: {
    columns: Array<{
      _key: string;
      columnLinks: Array<{
        _key: string;
        href: string | null;
        label: string | null;
      }> | null;
    }> | null;
    text: string | null;
  };
} | null;

// Source: src/sanity/query.ts
// Variable: ALL_TECH_STACK_QUERY
// Query: {  "techs": *[_type == 'technology' && defined(slug.current)]{  _id,  name,  "slug": slug.current,  "iconText": icon,  type, },  "total": count(*[_type == 'technology' && defined(slug.current)]),   "frontendCount": count(*[_type == 'technology' && type == 'frontend']),  "backendCount": count(*[_type == 'technology' && type == 'backend']),  "aiCount": count(*[_type == 'technology' && type == 'ai']),  "toolingCount": count(*[_type == 'technology' && type == 'tooling']),  "devopsCount": count(*[_type == 'technology' && type == 'devops']),  "badgeCount": count(*[_type == 'technology' && type == 'badge']),  "cloudCount": count(*[_type == 'technology' && type == 'cloud-and-infrastructure'])}
export type ALL_TECH_STACK_QUERY_RESULT = {
  techs: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    iconText: string | null;
    type:
      | 'ai'
      | 'backend'
      | 'badge'
      | 'cloud-and-infrastructure'
      | 'devops'
      | 'frontend'
      | 'tooling'
      | null;
  }>;
  total: number;
  frontendCount: number;
  backendCount: number;
  aiCount: number;
  toolingCount: number;
  devopsCount: number;
  badgeCount: number;
  cloudCount: number;
};

// Source: src/sanity/query.ts
// Variable: TECH_STACK_QUERY
// Query: *[_type == 'technology' && slug.current == $slug][0]{  name,  "slug": slug.current,  icon,  type,  _id }
export type TECH_STACK_QUERY_RESULT = {
  name: string | null;
  slug: string | null;
  icon: string | null;
  type:
    | 'ai'
    | 'backend'
    | 'badge'
    | 'cloud-and-infrastructure'
    | 'devops'
    | 'frontend'
    | 'tooling'
    | null;
  _id: string;
} | null;

// Source: src/sanity/query.ts
// Variable: ALL_HEROES_QUERY
// Query: {    "heroes": *[_type == 'hero'  && defined(slug.current)]{    _id,    name,    "slug": slug.current,    "imageUrl": mainImage.asset->url,    "imageAlt": mainImage.alt,  },     "total": count(*[_type == 'hero'              && defined(slug.current)])}
export type ALL_HEROES_QUERY_RESULT = {
  heroes: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    imageUrl: string | null;
    imageAlt: string | null;
  }>;
  total: number;
};

// Source: src/sanity/query.ts
// Variable: HERO_QUERY
// Query: *[_type == 'hero' && slug.current == $slug][0]{  _id,  name,  "slug": slug.current,  position,  title,  body,  "imageUrl": mainImage.asset->url,  "imageAlt": mainImage.alt,  actions[],  "imageAssetId": mainImage.asset._ref }
export type HERO_QUERY_RESULT = {
  _id: string;
  name: string | null;
  slug: string | null;
  position: Array<string> | null;
  title: string | null;
  body: BlockContent | null;
  imageUrl: string | null;
  imageAlt: string | null;
  actions: Array<{
    label?: string;
    href?: string;
    _key: string;
  }> | null;
  imageAssetId: string | null;
} | null;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == \'siteSetting\'][0]{\n  "imageUrl": primaryLogo.asset->url,\n  "imageAlt": primaryLogo.alt\n}': LOGO_QUERY_RESULT;
    '*[_type == \'siteSetting\'][0]{\n    "branding": {\n      siteName,\n      "primaryLogo": {\n        "imageUrl": primaryLogo.asset->url,\n        "imageAlt": primaryLogo.alt,\n      },\n      "secondaryLogo": {\n        "imageUrl": secondaryLogo.asset->url,\n        "imageAlt": secondaryLogo.alt,\n      },\n      socialLinks[]{\n        _key,\n        icon,\n        platform,\n        url\n      },\n      contactInfo{\n        city,\n        email,\n        githubURL,\n        leetCodeURL,\n        linkedInUrl,\n        state\n      },\n      mode[],\n      isAvailable,\n    },\n\n  "navigation": navigation[]{\n                  _key,\n                  href,\n                  isButton,\n                  label\n                },\n\n  "footer": {\n    "columns": footerColumns[]{\n      _key,\n      columnLinks[]{\n        _key,\n        href,\n        label\n      }\n    },\n    "text": footerText\n  }\n}': SETTING_QUERY_RESULT;
    "{\n  \"techs\": *[_type == 'technology'\n && defined(slug.current)]{\n  _id,\n  name,\n  \"slug\": slug.current,\n  \"iconText\": icon,\n  type,\n },\n  \"total\": count(*[_type == 'technology'\n && defined(slug.current)]),\n   \"frontendCount\": count(*[_type == 'technology'\n && type == 'frontend']),\n  \"backendCount\": count(*[_type == 'technology'\n && type == 'backend']),\n  \"aiCount\": count(*[_type == 'technology'\n && type == 'ai']),\n  \"toolingCount\": count(*[_type == 'technology'\n && type == 'tooling']),\n  \"devopsCount\": count(*[_type == 'technology'\n && type == 'devops']),\n  \"badgeCount\": count(*[_type == 'technology'\n && type == 'badge']),\n  \"cloudCount\": count(*[_type == 'technology'\n && type == 'cloud-and-infrastructure'])\n}": ALL_TECH_STACK_QUERY_RESULT;
    '*[_type == \'technology\'\n && slug.current == $slug][0]{\n  name,\n  "slug": slug.current,\n  icon,\n  type,\n  _id\n }': TECH_STACK_QUERY_RESULT;
    '{\n    "heroes": *[_type == \'hero\'\n  && defined(slug.current)]{\n    _id,\n    name,\n    "slug": slug.current,\n    "imageUrl": mainImage.asset->url,\n    "imageAlt": mainImage.alt,\n  }, \n    "total": count(*[_type == \'hero\'\n              && defined(slug.current)])\n}': ALL_HEROES_QUERY_RESULT;
    '*[_type == \'hero\'\n && slug.current == $slug][0]{\n  _id,\n  name,\n  "slug": slug.current,\n  position,\n  title,\n  body,\n  "imageUrl": mainImage.asset->url,\n  "imageAlt": mainImage.alt,\n  actions[],\n  "imageAssetId": mainImage.asset._ref\n }': HERO_QUERY_RESULT;
  }
}
