/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/extract.json
export type BlogCategoryReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'blogCategory';
};

export type BlogFocusReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'blogFocus';
};

export type Blog = {
  _id: string;
  _type: 'blog';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  publishedAt?: string;
  excerpt?: string;
  body?: BlockContent;
  mainImage?: ImageWithAlt;
  category?: BlogCategoryReference;
  focus?: BlogFocusReference;
  seo?: Seo;
};

export type Seo = {
  _type: 'seo';
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: ImageWithAlt;
  noIndex?: boolean;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type ImageWithAlt = {
  _type: 'imageWithAlt';
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
      listItem?: 'bullet';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }
  | ({
      _key: string;
    } & ImageWithAlt)
>;

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type BlogFocus = {
  _id: string;
  _type: 'blogFocus';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
};

export type BlogCategory = {
  _id: string;
  _type: 'blogCategory';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  mainImage?: ImageWithAlt;
};

export type Employment = {
  _id: string;
  _type: 'employment';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  startedAt?: string;
  endedAt?: string;
  body?: BlockContent;
  companyName?: string;
};

export type Project = {
  _id: string;
  _type: 'project';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  excerpt?: string;
  startedAt?: string;
  endedAt?: string;
  stacks?: Array<string>;
  links?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  body?: BlockContent;
  type?: 'property' | 'portfolio' | 'health-care' | 'e-commerce';
  mainImage?: ImageWithAlt;
  seo?: Seo;
};

export type Technology = {
  _id: string;
  _type: 'technology';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  icon?: string;
  type?:
    | 'frontend'
    | 'backend'
    | 'ai'
    | 'tooling'
    | 'devops'
    | 'badge'
    | 'cloud-and-infrastructure';
};

export type About = {
  _id: string;
  _type: 'about';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  body?: BlockContent;
  expertises?: Array<{
    title?: string;
    body?: BlockContent;
    _key: string;
  }>;
  workFlow?: Array<{
    title?: string;
    body?: string;
    _key: string;
  }>;
};

export type Hero = {
  _id: string;
  _type: 'hero';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  position?: Array<string>;
  title?: string;
  body?: BlockContent;
  mainImage?: ImageWithAlt;
  actions?: Array<{
    label?: string;
    href?: string;
    _key: string;
  }>;
};

export type SiteSetting = {
  _id: string;
  _type: 'siteSetting';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  primaryLogo?: ImageWithAlt;
  secondaryLogo?: ImageWithAlt;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  contactInfo?: {
    email?: string;
    linkedInUrl?: string;
    leetCodeURL?: string;
    gitHubURL?: string;
    city?: string;
    state?: string;
  };
  mode?: Array<string>;
  isAvailable?: boolean;
  availability?: string;
  navigation?: Array<{
    label?: string;
    href?: string;
    isButton?: boolean;
    _type: 'navLink';
    _key: string;
  }>;
  footerColumns?: Array<{
    columnTitle?: string;
    columnLinks?: Array<{
      label?: string;
      href?: string;
      _type: 'columnLink';
      _key: string;
    }>;
    _type: 'footerColumn';
    _key: string;
  }>;
  footerText?: string;
};

export type SocialLink = {
  _type: 'socialLink';
  platform?: 'linked-in' | 'git-hub' | 'leet-code';
  url?: string;
  icon?: string;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type MediaFolderReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'media.folder';
};

export type MediaFolder = {
  _id: string;
  _type: 'media.folder';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  parent?: MediaFolderReference;
};

export type MediaTag = {
  _id: string;
  _type: 'media.tag';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | BlogCategoryReference
  | BlogFocusReference
  | Blog
  | Seo
  | SanityImageAssetReference
  | ImageWithAlt
  | BlockContent
  | Slug
  | BlogFocus
  | BlogCategory
  | Employment
  | Project
  | Technology
  | About
  | Hero
  | SiteSetting
  | SocialLink
  | SanityImageCrop
  | SanityImageHotspot
  | MediaFolderReference
  | MediaFolder
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/query.ts
// Variable: ALL_BLOGS_QUERY
// Query: *[_type == 'blog' && defined(slug.current)]{    _id,    name,    "slug": slug.current,    publishedAt,    "imageUrl": mainImage.asset->url,    'imageAlt': mainImage.alt,    excerpt,    "focus": focus->name,    "category": category->name  }
export type ALL_BLOGS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  publishedAt: string | null;
  imageUrl: string | null;
  imageAlt: string | null;
  excerpt: string | null;
  focus: string | null;
  category: string | null;
}>;

// Source: src/sanity/query.ts
// Variable: ALL_BLOGS_QUERY_DESC
// Query: {  "blogs": *[_type == 'blog' && defined(slug.current)]  | order(publishedAt desc)  [$startIndex...$endIndex]{    _id,    name,    "slug": slug.current,    publishedAt,    "imageUrl": mainImage.asset->url,    'imageAlt': mainImage.alt,    excerpt,    "focus": focus->name,    "category": category->name  },  "total": count(*[_type == 'blog'                && defined(slug.current)])}
export type ALL_BLOGS_QUERY_DESC_RESULT = {
  blogs: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    publishedAt: string | null;
    imageUrl: string | null;
    imageAlt: string | null;
    excerpt: string | null;
    focus: string | null;
    category: string | null;
  }>;
  total: number;
};

// Source: src/sanity/query.ts
// Variable: ALL_BLOGS_QUERY_ASC
// Query: {  "blogs": *[_type == 'blog' && defined(slug.current)]  | order(publishedAt asc)  [$startIndex...$endIndex]{    _id,    name,    "slug": slug.current,    publishedAt,    "imageUrl": mainImage.asset->url,    'imageAlt': mainImage.alt,    excerpt,    "focus": focus->name,    "category": category->name  },  "total": count(*[_type == 'blog'                && defined(slug.current)])}
export type ALL_BLOGS_QUERY_ASC_RESULT = {
  blogs: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    publishedAt: string | null;
    imageUrl: string | null;
    imageAlt: string | null;
    excerpt: string | null;
    focus: string | null;
    category: string | null;
  }>;
  total: number;
};

// Source: src/sanity/query.ts
// Variable: BLOG_LOGO_QUERY
// Query: *[_type == 'siteSetting'][0]{  "imageUrl": secondaryLogo.asset->url,  "imageAlt": secondaryLogo.alt}
export type BLOG_LOGO_QUERY_RESULT = {
  imageUrl: string | null;
  imageAlt: string | null;
} | null;

// Source: src/sanity/query.ts
// Variable: ALL_CATEGORIES_QUERY
// Query: *[_type == 'blogCategory' && defined(slug.current)]  | order(_createdAt desc){    _id,    "imageUrl": mainImage.asset->url,    "imageAlt": mainImage.alt,    name,    "slug": slug.current  }
export type ALL_CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  imageUrl: string | null;
  imageAlt: string | null;
  name: string | null;
  slug: string | null;
}>;

// Source: src/sanity/query.ts
// Variable: BLOGS_BY_CATEGORY_QUERY
// Query: *[_type == 'blog' && defined(slug.current) && category->name match $category]{     _id,    name,    "slug": slug.current,    publishedAt,    "imageUrl": mainImage.asset->url,    'imageAlt': mainImage.alt,    excerpt,    "focus": focus->name,    "category": category->name  }
export type BLOGS_BY_CATEGORY_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  publishedAt: string | null;
  imageUrl: string | null;
  imageAlt: string | null;
  excerpt: string | null;
  focus: string | null;
  category: string | null;
}>;

// Source: src/sanity/query.ts
// Variable: BLOG_QUERY
// Query: *[_type == 'blog' && slug.current == $slug][0]{  name,  publishedAt,  body,  "imageUrl": mainImage.asset->url,  "imageAlt": mainImage.alt,  "category": category->name,  "categorySlug": category->slug.current,  "focus": focus->name,  "seo": seo{    metaTitle,    metaDescription,    "ogImage": ogImage.asset->url  },  "relatedBlogs": *[_type == 'blog'    && defined(slug.current)    && category._ref == ^.category._ref    && slug.current != $slug  ]{   _id,    name,    "slug": slug.current,    publishedAt,    "imageUrl": mainImage.asset->url,    'imageAlt': mainImage.alt,    excerpt,    "focus": focus->name,    "category": category->name  }}
export type BLOG_QUERY_RESULT = {
  name: string | null;
  publishedAt: string | null;
  body: BlockContent | null;
  imageUrl: string | null;
  imageAlt: string | null;
  category: string | null;
  categorySlug: string | null;
  focus: string | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    ogImage: string | null;
  } | null;
  relatedBlogs: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    publishedAt: string | null;
    imageUrl: string | null;
    imageAlt: string | null;
    excerpt: string | null;
    focus: string | null;
    category: string | null;
  }>;
} | null;

// Source: src/sanity/query.ts
// Variable: FOOTER_QUERY
// Query: *[_type == 'siteSetting'][0]{  "logoUrl": secondaryLogo.asset->url,  "logoAlt": secondaryLogo.alt,  socialLinks[]{    _key,    icon,    platform,    url  },}
export type FOOTER_QUERY_RESULT = {
  logoUrl: string | null;
  logoAlt: string | null;
  socialLinks: Array<{
    _key: string;
    icon: string | null;
    platform: 'git-hub' | 'leet-code' | 'linked-in' | null;
    url: string | null;
  }> | null;
} | null;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == \'blog\'\n && defined(slug.current)]{\n    _id,\n    name,\n    "slug": slug.current,\n    publishedAt,\n    "imageUrl": mainImage.asset->url,\n    \'imageAlt\': mainImage.alt,\n    excerpt,\n    "focus": focus->name,\n    "category": category->name\n  }': ALL_BLOGS_QUERY_RESULT;
    '{\n  "blogs": *[_type == \'blog\'\n && defined(slug.current)]\n  | order(publishedAt desc)\n  [$startIndex...$endIndex]{\n    _id,\n    name,\n    "slug": slug.current,\n    publishedAt,\n    "imageUrl": mainImage.asset->url,\n    \'imageAlt\': mainImage.alt,\n    excerpt,\n    "focus": focus->name,\n    "category": category->name\n  },\n  "total": count(*[_type == \'blog\'\n                && defined(slug.current)])\n}': ALL_BLOGS_QUERY_DESC_RESULT;
    '{\n  "blogs": *[_type == \'blog\'\n && defined(slug.current)]\n  | order(publishedAt asc)\n  [$startIndex...$endIndex]{\n    _id,\n    name,\n    "slug": slug.current,\n    publishedAt,\n    "imageUrl": mainImage.asset->url,\n    \'imageAlt\': mainImage.alt,\n    excerpt,\n    "focus": focus->name,\n    "category": category->name\n  },\n  "total": count(*[_type == \'blog\'\n                && defined(slug.current)])\n}': ALL_BLOGS_QUERY_ASC_RESULT;
    '*[_type == \'siteSetting\'][0]{\n  "imageUrl": secondaryLogo.asset->url,\n  "imageAlt": secondaryLogo.alt\n}': BLOG_LOGO_QUERY_RESULT;
    '*[_type == \'blogCategory\'\n && defined(slug.current)]\n  | order(_createdAt desc){\n    _id,\n    "imageUrl": mainImage.asset->url,\n    "imageAlt": mainImage.alt,\n    name,\n    "slug": slug.current\n  }': ALL_CATEGORIES_QUERY_RESULT;
    '*[_type == \'blog\'\n && defined(slug.current)\n && category->name match $category]{\n     _id,\n    name,\n    "slug": slug.current,\n    publishedAt,\n    "imageUrl": mainImage.asset->url,\n    \'imageAlt\': mainImage.alt,\n    excerpt,\n    "focus": focus->name,\n    "category": category->name\n  }': BLOGS_BY_CATEGORY_QUERY_RESULT;
    '*[_type == \'blog\' && slug.current == $slug][0]{\n  name,\n  publishedAt,\n  body,\n  "imageUrl": mainImage.asset->url,\n  "imageAlt": mainImage.alt,\n  "category": category->name,\n  "categorySlug": category->slug.current,\n  "focus": focus->name,\n  "seo": seo{\n    metaTitle,\n    metaDescription,\n    "ogImage": ogImage.asset->url\n  },\n  "relatedBlogs": *[_type == \'blog\'\n    && defined(slug.current)\n    && category._ref == ^.category._ref\n    && slug.current != $slug\n  ]{\n   _id,\n    name,\n    "slug": slug.current,\n    publishedAt,\n    "imageUrl": mainImage.asset->url,\n    \'imageAlt\': mainImage.alt,\n    excerpt,\n    "focus": focus->name,\n    "category": category->name\n  }\n}': BLOG_QUERY_RESULT;
    '*[_type == \'siteSetting\'][0]{\n  "logoUrl": secondaryLogo.asset->url,\n  "logoAlt": secondaryLogo.alt,\n  socialLinks[]{\n    _key,\n    icon,\n    platform,\n    url\n  },\n}': FOOTER_QUERY_RESULT;
  }
}
