/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/extract.json
export type Employment = {
  _id: string;
  _type: 'employment';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  startedAt?: string;
  endedAt?: string;
  body?: BlockContent;
  companyName?: string;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
      listItem?: 'bullet';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }
  | ({
      _key: string;
    } & ImageWithAlt)
>;

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type Project = {
  _id: string;
  _type: 'project';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  excerpt?: string;
  startedAt?: string;
  endedAt?: string;
  stacks?: Array<string>;
  links?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  body?: BlockContent;
  type?: string;
  mainImage?: ImageWithAlt;
  seo?: Seo;
};

export type Seo = {
  _type: 'seo';
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: ImageWithAlt;
  noIndex?: boolean;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type ImageWithAlt = {
  _type: 'imageWithAlt';
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
};

export type Technology = {
  _id: string;
  _type: 'technology';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  icon?: string;
  type?:
    | 'frontend'
    | 'backend'
    | 'ai'
    | 'tooling'
    | 'devops'
    | 'badge'
    | 'cloud-and-infrastructure';
};

export type About = {
  _id: string;
  _type: 'about';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  body?: BlockContent;
  workFlow?: Array<{
    title?: string;
    body?: string;
    _key: string;
  }>;
};

export type Hero = {
  _id: string;
  _type: 'hero';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  position?: Array<string>;
  title?: string;
  body?: BlockContent;
  mainImage?: ImageWithAlt;
  actions?: Array<{
    label?: string;
    href?: string;
    _key: string;
  }>;
};

export type SiteSetting = {
  _id: string;
  _type: 'siteSetting';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  primaryLogo?: ImageWithAlt;
  secondaryLogo?: ImageWithAlt;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  contactInfo?: {
    email?: string;
    linkedInUrl?: string;
    leetCodeURL?: string;
    gitHubURL?: string;
    city?: string;
    state?: string;
  };
  mode?: Array<string>;
  isAvailable?: boolean;
  availability?: string;
  navigation?: Array<{
    label?: string;
    href?: string;
    isButton?: boolean;
    _type: 'navLink';
    _key: string;
  }>;
  footerColumns?: Array<{
    columnTitle?: string;
    columnLinks?: Array<{
      label?: string;
      href?: string;
      _type: 'columnLink';
      _key: string;
    }>;
    _type: 'footerColumn';
    _key: string;
  }>;
  footerText?: string;
};

export type SocialLink = {
  _type: 'socialLink';
  platform?: 'linked-in' | 'git-hub' | 'leet-code';
  url?: string;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type MediaFolderReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'media.folder';
};

export type MediaFolder = {
  _id: string;
  _type: 'media.folder';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  parent?: MediaFolderReference;
};

export type MediaTag = {
  _id: string;
  _type: 'media.tag';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Employment
  | BlockContent
  | Slug
  | Project
  | Seo
  | SanityImageAssetReference
  | ImageWithAlt
  | Technology
  | About
  | Hero
  | SiteSetting
  | SocialLink
  | SanityImageCrop
  | SanityImageHotspot
  | MediaFolderReference
  | MediaFolder
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/query.ts
// Variable: HEADER_QUERY
// Query: *[_type == 'siteSetting'][0]{  contactInfo,  navigation[],  "logoUrl": primaryLogo.asset->url,  "logoAlt": primaryLogo.alt,}
export type HEADER_QUERY_RESULT = {
  contactInfo: {
    email?: string;
    linkedInUrl?: string;
    leetCodeURL?: string;
    gitHubURL?: string;
    city?: string;
    state?: string;
  } | null;
  navigation: Array<{
    label?: string;
    href?: string;
    isButton?: boolean;
    _type: 'navLink';
    _key: string;
  }> | null;
  logoUrl: string | null;
  logoAlt: string | null;
} | null;

// Source: src/sanity/query.ts
// Variable: FOOTER_QUERY
// Query: *[_type == 'siteSetting'][0]{  contactInfo,  footerColumns,  "logoUrl": primaryLogo.asset->url,  "logoAlt": primaryLogo.alt,  socialLinks[]{    _key,    icon,    platform,    url  },  footerText,}
export type FOOTER_QUERY_RESULT = {
  contactInfo: {
    email?: string;
    linkedInUrl?: string;
    leetCodeURL?: string;
    gitHubURL?: string;
    city?: string;
    state?: string;
  } | null;
  footerColumns: Array<{
    columnTitle?: string;
    columnLinks?: Array<{
      label?: string;
      href?: string;
      _type: 'columnLink';
      _key: string;
    }>;
    _type: 'footerColumn';
    _key: string;
  }> | null;
  logoUrl: string | null;
  logoAlt: string | null;
  socialLinks: Array<{
    _key: string;
    icon: null;
    platform: 'git-hub' | 'leet-code' | 'linked-in' | null;
    url: string | null;
  }> | null;
  footerText: string | null;
} | null;

// Source: src/sanity/query.ts
// Variable: HOME_PAGE_QUERY
// Query: {  "settings": *[_type == 'siteSetting'][0]{      contactInfo,      "logoUrl": primaryLogo.asset->url,      "logoAlt": primaryLogo.alt,      socialLinks[],      mode  },  "hero": *[_type == 'hero'   && slug.current == "home-page"][0]{      _id,      title,      body,      actions[]{        _key,        label,        href      },      "imageUrl": mainImage.asset->url,      "imageAlt": mainImage.alt,      position[],   },  "technology": *[_type == 'technology'   && defined(slug.current)]{      _id,      name,      icon  },  "projects": *[_type == 'project'   && defined(slug.current)]    | order(createdAt){      _id,      name,      "slug": slug.current,      startedAt,      endedAt,      excerpt,      links[]{        _key,        label,        url      },      stacks[],      type    },  "employments": *[_type == 'employment'   && defined(slug.current)]    | order(startedAt desc){      _id,      body,      name,      companyName,      startedAt,      endedAt   },  "about": *[_type == 'about'    && slug.current == 'about'][0]{      body, }}
export type HOME_PAGE_QUERY_RESULT = {
  settings: {
    contactInfo: {
      email?: string;
      linkedInUrl?: string;
      leetCodeURL?: string;
      gitHubURL?: string;
      city?: string;
      state?: string;
    } | null;
    logoUrl: string | null;
    logoAlt: string | null;
    socialLinks: Array<
      {
        _key: string;
      } & SocialLink
    > | null;
    mode: Array<string> | null;
  } | null;
  hero: {
    _id: string;
    title: string | null;
    body: BlockContent | null;
    actions: Array<{
      _key: string;
      label: string | null;
      href: string | null;
    }> | null;
    imageUrl: string | null;
    imageAlt: string | null;
    position: Array<string> | null;
  } | null;
  technology: Array<{
    _id: string;
    name: string | null;
    icon: string | null;
  }>;
  projects: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    startedAt: string | null;
    endedAt: string | null;
    excerpt: string | null;
    links: Array<{
      _key: string;
      label: string | null;
      url: string | null;
    }> | null;
    stacks: Array<string> | null;
    type: string | null;
  }>;
  employments: Array<{
    _id: string;
    body: BlockContent | null;
    name: string | null;
    companyName: string | null;
    startedAt: string | null;
    endedAt: string | null;
  }>;
  about: {
    body: BlockContent | null;
  } | null;
};

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == \'siteSetting\'][0]{\n  contactInfo,\n  navigation[],\n  "logoUrl": primaryLogo.asset->url,\n  "logoAlt": primaryLogo.alt,\n}': HEADER_QUERY_RESULT;
    '*[_type == \'siteSetting\'][0]{\n  contactInfo,\n  footerColumns,\n  "logoUrl": primaryLogo.asset->url,\n  "logoAlt": primaryLogo.alt,\n  socialLinks[]{\n    _key,\n    icon,\n    platform,\n    url\n  },\n  footerText,\n}': FOOTER_QUERY_RESULT;
    '{\n  "settings": *[_type == \'siteSetting\'][0]{\n      contactInfo,\n      "logoUrl": primaryLogo.asset->url,\n      "logoAlt": primaryLogo.alt,\n      socialLinks[],\n      mode\n  },\n  "hero": *[_type == \'hero\'\n   && slug.current == "home-page"][0]{\n      _id,\n      title,\n      body,\n      actions[]{\n        _key,\n        label,\n        href\n      },\n      "imageUrl": mainImage.asset->url,\n      "imageAlt": mainImage.alt,\n      position[],\n   },\n  "technology": *[_type == \'technology\'\n   && defined(slug.current)]{\n      _id,\n      name,\n      icon\n  },\n  "projects": *[_type == \'project\'\n   && defined(slug.current)]\n    | order(createdAt){\n      _id,\n      name,\n      "slug": slug.current,\n      startedAt,\n      endedAt,\n      excerpt,\n      links[]{\n        _key,\n        label,\n        url\n      },\n      stacks[],\n      type\n    },\n  "employments": *[_type == \'employment\'\n   && defined(slug.current)]\n    | order(startedAt desc){\n      _id,\n      body,\n      name,\n      companyName,\n      startedAt,\n      endedAt\n   },\n  "about": *[_type == \'about\'\n    && slug.current == \'about\'][0]{\n      body,\n }\n}': HOME_PAGE_QUERY_RESULT;
  }
}
